// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"redis-demo/internal/dao/internal"
)

// notificationDao is the data access object for the table notification.
// You can define custom methods on it to extend its functionality as needed.
type notificationDao struct {
	*internal.NotificationDao
}

var (
	// Notification is a globally accessible object for table notification operations.
	Notification = notificationDao{internal.NewNotificationDao()}
)

// Add your custom methods and functionality below.
