// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"redis-demo/internal/dao/internal"
)

// taskCommentDao is the data access object for the table task_comment.
// You can define custom methods on it to extend its functionality as needed.
type taskCommentDao struct {
	*internal.TaskCommentDao
}

var (
	// TaskComment is a globally accessible object for table task_comment operations.
	TaskComment = taskCommentDao{internal.NewTaskCommentDao()}
)

// Add your custom methods and functionality below.
