// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"redis-demo/internal/dao/internal"
)

// teamMemberDao is the data access object for the table team_member.
// You can define custom methods on it to extend its functionality as needed.
type teamMemberDao struct {
	*internal.TeamMemberDao
}

var (
	// TeamMember is a globally accessible object for table team_member operations.
	TeamMember = teamMemberDao{internal.NewTeamMemberDao()}
)

// Add your custom methods and functionality below.
